name: ol-rl
on: push

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
      - name: Setup MinGW
        uses: egor-tensin/setup-mingw@v2
        with:
          platform: any
      - name: Setup Emscripten
        uses: mymindstorm/setup-emsdk@v14
      - name: Setup wine
        shell: bash
        run: |
          sudo dpkg --add-architecture i386
          sudo apt install -y wine
      - name: Build slgj-2024
        shell: bash
        run: |
          ./build.sh
      - name: Upload as artifact
        uses: actions/upload-artifact@v3
        with:
          name: slgj-2024
          path: build/
